used:
    - thread_tags: Thread sensor tags sending UDP packets to MQTT
    - heat_cut : cuts a rooms heat when a room's window is open
    - influx_mqtt: mqtt 2 influx
    - bathroom: manages the bathroom fan and light from switch and sensors
    - hue : hue light control
    - zigbee2mqtt: 
    - pc_power: 
    - influxdb: 
    - mosquitto: eclipse-mosquitto

not_used:
    - nrf_mesh
    - roll
    - lapse
    - lifx
    - watch_bots
    - home_status

other:
    webapps:
        - overview
        - bed_heating
        - heating
        - leds_panel
        - mesh_view
        - zigbee_graph_view
        - next-home-control
    python:
        - heat_cut : cuts a rooms heat when a room's window is open
        - nrf_mesh: custom RF devices to mqtt
        - influx_mqtt: mqtt 2 influx
        - bathroom_fan
        - hue : hue light control
        - home_status
        - thread_tags: udp2mqtt
    nodejs:
        - lapse
        - lifx
        - pc_power
        - watch_bots
        - roll
    installed:
        - influxdb
        - openthread : https://www.homesmartmesh.com/docs/networks/thread/#raspberry-pi
    docker:
        - influxdb
        - grafana
        - homeassistant
        - zigAssMano
        - zigAssLifo
        - deconz
