server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
#- job_name: system
#  static_configs:
#  - targets:
#      - localhost
#    labels:
#      job: varlogs
#      __path__: /var/log/host/*log
  - job_name: smarthome
    static_configs:
    - targets:
        - localhost
      labels:
        job: smarthome
        __path__: /var/log/share/*.log
  
  - job_name: zigbee
    static_configs:
    - targets:
        - localhost
      labels:
        job: zigbee
        __path__: /var/log/zigbee/**/*.log
  
  - job_name: astro
    journal:
      max_age: 12h
    relabel_configs:
      # Keep only log lines whose systemd unit is astro.service
      - source_labels: ['__journal__systemd_unit']
        regex: astro\.service
        action: keep

      # Rename Promtailâ€™s internal label __journal__systemd_unit to a simpler "unit"
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'

      - source_labels: []
        target_label: 'host'
        replacement: 'silent'

      # 4) Add an extra label 'app'
      - source_labels: []
        target_label: 'app'
        replacement: 'astro'

  - job_name: systemd_services
    journal:
      max_age: 24h
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: (thread_tags|heat_cut|influx_mqtt|bathroom|hue|zigbee2mqtt|pc_power|influxdb|mosquitto)\.service
        action: keep
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: []
        target_label: 'job'
        replacement: 'systemd'
